services:
  #if you want to use ollama as LLM provider, uncomment this service
  #ollama:
  #  image: ollama/ollama
  #  ports:
  #    - "11434:11434"
  ai:
    build: .
    container_name: bydgoszcz-ai-test
    ports:
      - "5000:5000"
    #depends_on:
    #  - ollama
    env_file:
      - .env
    environment:
      - LLM_MODEL=${LLM_MODEL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=false
      - FLASK_ENV=production
      - MAX_TOKENS=${MAX_TOKENS}
      - TEMPERATURE=${TEMPERATURE}
      #- OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_BASE_URL=http://ollama:11434
    
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
